### PR TITLE
Upgrade to Lucene 7.x 

### PR DESCRIPTION
**Pull request by reckart**
Upgrade components 

Based on: https://github.com/aschwarte10/rdf4j-storage/tree/issues/%2377-luceneUpdate-7

### CODE REVIEW

**Comment by rcffc** [comment]
I tried to change the imports in inception-kb but it seems like it doesn't find the package. 
selection_093

**Comment by rcffc** [comment]
Console Output:
[WARNING] The POM for org.eclipse.rdf4j:rdf4j-query:jar:2.4-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.eclipse.rdf4j:rdf4j-queryalgebra-model:jar:2.4-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.eclipse.rdf4j:rdf4j-model:jar:2.4-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.eclipse.rdf4j:rdf4j-util:jar:2.4-SNAPSHOT is missing, no dependency information available

**Comment by reckart** [comment]
@rcffc I have committed a fix for the missing dependencies in the other branch. Let's wait until that one completes.

**Comment by reckart** [comment]
@rcffc https://github.com/inception-project/inception/pull/490 upgrades MTAS to 7.3.0.3 which uses Lucene 7.3.0.

**Pull request merged**
